(* Generates [brisk_ppx_compat.ml] with an implementation matching the
   flavour of ppxlib in the current switch.

   ppxlib normally pins its [Parsetree] to a single version so a ppx can be
   written once and work across every OCaml release ppxlib supports. OxCaml
   ships a *patched* ppxlib whose AST is extended with Jane Street constructs
   (jkinds, modes), which breaks that guarantee for the handful of nodes we
   destructure or build by hand:

     - [Pexp_newtype] gains a [jkind_annotation option]:
         upstream : string loc * expression                       (2 args)
         OxCaml   : string loc * jkind_annotation option * expr   (3 args)
     - [Pexp_function]'s middle field changes from [type_constraint option]
       to a [function_constraint] record.
     - [Pexp_let] gains a leading [mutable_flag] (for [let mutable]).
     - [Ast_pattern.value_binding] takes [~constraint_] upstream but only
       [~pat]/[~expr] on OxCaml.

   We can't write a single pattern/constructor that type-checks against both
   shapes, so we detect the flavour here and emit the divergent primitives
   accordingly. Everything else in the ppx is either version-stable already or
   built through [Ast_builder], whose [pexp_newtype] helper hides the arity on
   both. *)

module C = Configurator.V1

(* OxCaml is the only flavour that patches ppxlib's AST, and its compiler is
   the only one that reports these fields in [ocamlc -config]. Keying on the
   compiler is a reliable proxy: OxCaml's ppxlib is only ever paired with the
   OxCaml compiler. *)
let is_oxcaml c =
  let flag name =
    match C.ocaml_config_var c name with Some "true" -> true | _ -> false
  in
  flag "flambda_backend" || flag "ox"

let upstream =
  {ocaml|(* Generated by config/discover.ml -- do not edit.
   Upstream ppxlib AST: [Pexp_newtype] takes 2 args, [Pexp_function]'s
   constraint is a [type_constraint option], and [Ast_pattern.value_binding]
   takes a [~constraint_] argument. *)

let match_pexp_newtype (desc : Ppxlib.Ast.expression_desc) =
  match desc with
  | Ppxlib.Ast.Pexp_newtype (name, body) -> Some (name, body)
  | _ -> None

let no_function_constraint : Ppxlib.Ast.type_constraint option = None

let match_pexp_let (desc : Ppxlib.Ast.expression_desc) =
  match desc with
  | Ppxlib.Ast.Pexp_let (rec_flag, bindings, body) ->
      Some (rec_flag, bindings, body)
  | _ -> None

let value_binding_pat ~pat ~expr =
  Ppxlib.Ast_pattern.value_binding ~pat ~expr
    ~constraint_:Ppxlib.Ast_pattern.drop
|ocaml}

let oxcaml =
  {ocaml|(* Generated by config/discover.ml -- do not edit.
   OxCaml ppxlib AST: [Pexp_newtype] carries a jkind annotation,
   [Pexp_function]'s constraint is a [function_constraint] record, and
   [Ast_pattern.value_binding] exposes only [~pat]/[~expr]. *)

let match_pexp_newtype (desc : Ppxlib.Ast.expression_desc) =
  match desc with
  | Ppxlib.Ast.Pexp_newtype (name, _jkind, body) -> Some (name, body)
  | _ -> None

let no_function_constraint : Ppxlib.Ast.function_constraint =
  Ppxlib.Ast.
    { mode_annotations = []
    ; ret_mode_annotations = []
    ; ret_type_constraint = None
    }

let match_pexp_let (desc : Ppxlib.Ast.expression_desc) =
  match desc with
  | Ppxlib.Ast.Pexp_let (_mutable, rec_flag, bindings, body) ->
      Some (rec_flag, bindings, body)
  | _ -> None

let value_binding_pat ~pat ~expr =
  Ppxlib.Ast_pattern.value_binding ~pat ~expr
|ocaml}

let () =
  C.main ~name:"brisk_ppx" (fun c ->
      let contents = if is_oxcaml c then oxcaml else upstream in
      let oc = open_out "brisk_ppx_compat.ml" in
      output_string oc contents;
      close_out oc)
