parameters:
  OCAML_VERSION: "4.07"

steps:
  - script: |
      esy "@package-ci-${{parameters.OCAML_VERSION}}" install
      esy "@package-ci-${{parameters.OCAML_VERSION}}" build
    displayName: "Install and build ${{parameters.OCAML_VERSION}}"
